### ISSUE TITLE
No recursion?

### ISSUE THREAD

**Issue by bittaurus** [tonmanna/sanitizeSQL#1]
This appears to do simple regex replace to eliminate substrings.

But, it only processes each substring once?

What would happen if you passed the query:

"SELECTSELECT current_database()current_database()"

wouldnt it replace the substring "SELECT current_database()" with ' ', resulting in:

"SELECT current_database()"

**Comment by tonmanna** [comment]
Thanks for your report. 
I try to refactor the code to support the case of the recursion query. Please update to version 1.0.9
